unix {
  nodaemon
  log /var/log/vpp/vpp.log
  full-coredump
  cli-listen /run/vpp/cli.sock
  gid vpp
  exec /etc/vpp/config/bootstrap.vpp
}

api-trace { on }
api-segment { gid vpp }
socksvr { default }

#memory {
  #main-heap-size 1G
  #main-heap-page-size 2M
#}

cpu {
  main-core 1
  workers 2-3
}

buffers {
  #buffers-per-numa 128000
  #default data-size 2048
  page-size 2M
}

dpdk {
  dev 0000:02:00.0
  dev 0000:03:00.0
  uio-driver vfio-pci
}

#statseg {
#  size 1G
#  page-size default-hugepage
#  per-node-counters off
#}

plugins {
  plugin default { disable }
  plugin dpdk_plugin.so { enable }
  plugin memif_plugin.so { enable }
  plugin acl_plugin.so { enable }
  plugin ping_plugin.so { enable }
#  plugin lacp_plugin.so { enable }
#  plugin linux_cp_plugin.so { enable }
#  plugin linux_nl_plugin.so { enable }
#  plugin sflow_plugin.so { enable }
}

logging {
  default-log-level info
  default-syslog-log-level notice
  class sflow/all { rate-limit 10000 level debug syslog-level debug }
}